#!/usr/bin/env python
"""
gen_eqns.py
===========
Emit the renamed sCO2 recompression-cycle model (checkpoint C2.3).

The legacy model indexes every state in one flat array, 1..12 for the cycle and
12 + k*d_p + n for the four recuperator sides. Three of the bugs fixed in Phase 0
were index-arithmetic errors in exactly that scheme. This generator emits the same
physics with named scalars and per-side arrays, so no equation contains
12 + k*d_p + n arithmetic anywhere.

Physics is UNCHANGED. Every equation below is a renaming of one in eqns.txt as of
the stage-5 model. Two structural artefacts are dropped deliberately:

  * P[333], a phantom created by `P[p] = P[p+1]` running one past the LTR
    low-pressure chain. The named chain cannot express it.
  * The paired REFPROP TP calls (one for h, one for s, same inputs) are merged
    into one call per point - checkpoint C6.1, a straight 2x on the dominant cost.

Naming comes from gen_state_map.py; change CYCLE_STATES there and re-run both.

Usage:
    python gen_eqns.py --d-p 80 --out ../eqns_named.txt
"""

from __future__ import annotations

import argparse
from pathlib import Path

from gen_state_map import CYCLE_STATES, SIDES

# name of each cycle state, by legacy index
S = {i: v[0] for i, v in CYCLE_STATES.items()}
SIDE_NAMES = [b for _, b, _, _ in SIDES]          # HTR_HP, HTR_LP, LTR_HP, LTR_LP

L: list[str] = []
TABLE_HOM = False


def w(*lines: str) -> None:
    L.extend(lines)


def banner(title: str) -> None:
    w("", '"' + "=" * 72, f"  {title}", " " + "=" * 72 + '"')


# =========================================================================
def header() -> None:
    w("$UnitSystem SI K bar J mass",
      "",
      "FUNCTION interpolate2dm(F$,X,Y)",
      "\tCol=LookupCol1(F$,1,X)",
      "\tRow=LookupRow1(F$,1,Y)",
      "\tinterpolate2dm=Lookup(F$,Row,Col)",
      'END "!2-D interpolation"',
      "",
      "$ConvertEESREFPROPUnits /mass",
      "$INCLUDE C:\\EES64\\Userlib64\\EES_REFPROP\\EES_REFPROP.TXT",
      "",
      '"Generated by python/gen_eqns.py from mapping/state_map.csv - do not hand-edit.',
      ' Physics is identical to the stage-5 model; only names change.',
      ' Legacy index for every variable is in mapping/state_map.csv."')


def inputs() -> None:
    banner("INPUTS AND DEGREES OF FREEDOM")
    w("Mixture$='CarbonDioxide+Ethane'",
      "MW_CO2    = 44.01 [kg/kmol]",
      "MW_second = 30.07 [kg/kmol]   \"ETHANE. Argon = 39.948, SO2 = 64.06. Must match Mixture$.\"",
      "x_CO2 = 0.91                  \"mole fraction\"",
      "x_CO2 = (z_CO2/MW_CO2)/((z_CO2/MW_CO2)+((1-z_CO2)/MW_second))   \"-> mass fraction z_CO2\"",
      "",
      "A_tube         = 4.2 [m^2]    \"DOF: area per tube\"",
      "r              = 0.5          \"DOF: HX area fraction, A_LTR = r*A_tot\"",
      "frac_recomp    = 0.4          \"DOF: recompression fraction\"",
      "m_dot_tube_hot = 0.093 [kg/s]",
      "N_tubes        = 150",
      "d_p            = 80           \"discrete points per recuperator side\"",
      "D              = 0.02 [m]",
      "T_cold         = 300 [K]",
      "T_hot          = 850 [K]",
      "P_H            = 220 [bar]",
      "P_L - P_crit   = 10 [bar]",
      "",
      "CALL EES_REFPROP(Mixture$,100,z_CO2 : T_crit,P_crit,rho_crit)",
      "",
      "eta_comp1 = 0.88   \"isentropic efficiencies, previously buried as literals\"",
      "eta_comp2 = 0.89",
      "eta_turb  = 0.93")


def areas_flows() -> None:
    banner("AREAS AND MASS FLOWS")
    w("A_tot = N_tubes*A_tube",
      "A_LTR = r*A_tot",
      "A_HTR = (1-r)*A_tot",
      '"pi# replaces the legacy 3.14 (a 0.05 percent correction). Kept: C2.5 was proven',
      ' with every pi-independent quantity bit-identical, so this is the only deviation."',
      "A_flow_tube = pi#*D*D/4",
      "A_HTR_tube  = A_HTR/N_tubes",
      "A_LTR_tube  = A_LTR/N_tubes",
      "L_HTR = A_HTR_tube/(pi#*D)",
      "L_LTR = A_LTR_tube/(pi#*D)",
      "",
      "m_dot_tube_cold  = (1-frac_recomp)*m_dot_tube_hot",
      "m_dot_hot  = N_tubes*m_dot_tube_hot    \"full circulating flow\"",
      "m_dot_cold = N_tubes*m_dot_tube_cold   \"main branch, through cooler and LTR high-pressure side\"",
      "m_dot_recomp = m_dot_hot - m_dot_cold  \"recompression branch\"",
      "",
      '"per-state mass flows, named"')
    hot = ["HTR_HP_out", "turb_in", "turb_out", "HTR_LP_out", "LTR_LP_out", "mix_out"]
    cold = ["comp1_in", "comp1_out", "cooler_in", "LTR_HP_out"]
    for n in hot:
        w(f"m_dot_{n} = m_dot_hot")
    for n in cold:
        w(f"m_dot_{n} = m_dot_cold")
    w("m_dot_comp2_in  = m_dot_recomp",
      "m_dot_comp2_out = m_dot_recomp")


def pressures() -> None:
    banner("PRESSURE NETWORK")
    w('"Every drop comes from the LOCAL density (C5.1, landed 2026-09-08). The frozen',
      '  rho = 1.83 / mu = 1.71e-5 block that used to live here is gone, along with the',
      '  hom_dP homotopy that bridged to it and the $CheckUnits Off guard that hid its',
      '  dimensional error. eta moved 0.4332 -> 0.4631 when this landed."',
      "",
      '"fixed pressures"',
      "P_comp1_out = P_H",
      "P_turb_out  = P_L",
      "",
      '"mixing junction: one junction, one pressure (C0.9)."',
      "P_comp2_out = P_LTR_HP_out",
      "P_mix_out   = P_LTR_HP_out",
      "")

    # side, inlet state, outlet state, direction
    chains = [
        ("HTR_HP", S[12], S[4],  "fwd"),
        ("HTR_LP", S[6],  S[7],  "rev"),
        ("LTR_HP", S[2],  S[11], "fwd"),
        ("LTR_LP", S[7],  S[8],  "rev"),
    ]
    for base, s_in, s_out, direction in chains:
        if direction == "fwd":
            w(f'"{base}: flows {s_in} -> n=1..d_p -> {s_out}. d_p+1 segments, each',
              '  charged at the density of the point UPSTREAM of it."',
              f"P_{base}[1] = P_{s_in} - dPin_{base}",
              "DUPLICATE n=2,d_p",
              f"  P_{base}[n] = P_{base}[n-1] - dP_seg_{base}[n-1]",
              "END",
              f"P_{s_out} = P_{base}[d_p] - dP_seg_{base}[d_p]",
              "")
        else:
            w(f'"{base}: flows {s_in} -> n=d_p..1 -> {s_out}. d_p+1 segments, each',
              '  charged at the density of the point UPSTREAM of it."',
              f"P_{base}[d_p] = P_{s_in} - dPin_{base}",
              "DUPLICATE n=1,d_p-1",
              f"  P_{base}[n] = P_{base}[n+1] - dP_seg_{base}[n+1]",
              "END",
              f"P_{s_out} = P_{base}[1] - dP_seg_{base}[1]",
              "")
    w("P_comp2_in  = P_LTR_LP_out",
      "P_cooler_in = P_LTR_LP_out",
      "P_comp1_in  = P_cooler_in",
      "P_turb_in   = P_HTR_HP_out")


def _lk(prop: str, P: str, T: str) -> str:
    """One property lookup, optionally blended between the old and new tables.

    hom_tab = 0 reproduces the old tables exactly, so the previously converged
    solution is the starting point; 1 is the regenerated tables. Both sets must be
    loaded and named <prop>_old and <prop>_new.

    Note the old tables cover only 80-220 bar / 300-850 K, so they will emit
    out-of-range warnings at EVERY hom_tab including 1, where they are multiplied
    by zero. Ignore them during the sweep, and regenerate without --table-homotopy
    once it lands.
    """
    if not TABLE_HOM:
        return f"interpolate2dm('{prop}', {P}, {T})"
    return (f"((1-hom_tab)*interpolate2dm('{prop}_old', {P}, {T})"
            f" + hom_tab*interpolate2dm('{prop}_new', {P}, {T}))")


def transport() -> None:
    banner("TRANSPORT PROPERTIES AND FILM COEFFICIENTS")
    if TABLE_HOM:
        w('"TABLE HOMOTOPY. 0 = old tables, 1 = regenerated. Sweep on a Parametric',
          '  Table with Update Guess Values. The regenerated set changes three things',
          '  at once - coverage 60-240 bar vs 80-220, 1 K resolution through the',
          '  pseudo-critical ridge, and the composition fix from 0.8736 to 0.91 mole',
          '  CO2 - so if this stalls, the intermediate tables isolate which one."',
          "hom_tab = 0 [-]",
          "$VarInfo hom_tab Guess=0 Lower=0 Upper=1 Units='-'",
          "")
    w("k_ss  = 22 [W/m-K]",
      "L_ss  = 0.008 [m]",
      "R_cond = L_ss/k_ss   \"wall resistance, counted ONCE per cell (C0.11)\"",
      "")
    for base in SIDE_NAMES:
        flow = "m_dot_tube_cold" if base == "LTR_HP" else "m_dot_tube_hot"
        w(f'"--- {base} ---"',
          f"DUPLICATE n=1,d_p",
          f"  cp_{base}[n] = " + _lk('cp',  f"P_{base}[n]*Convert(bar,Pa)", f"T_{base}[n]"),
          f"  k_{base}[n]  = " + _lk('k',   f"P_{base}[n]*Convert(bar,Pa)", f"T_{base}[n]"),
          f"  mu_{base}[n] = " + _lk('eta', f"P_{base}[n]*Convert(bar,Pa)", f"T_{base}[n]"),
          f"  Pr_{base}[n] = mu_{base}[n]*cp_{base}[n]/k_{base}[n]",
          f"  Re_{base}[n] = {flow}*D/(A_flow_tube*mu_{base}[n])",
          f"  f_{base}[n]  = (1.82*Log10(Re_{base}[n]) - 1.64)^(-2)",
          f"  Nu_{base}[n] = ((f_{base}[n]/8)*(Re_{base}[n]-1000)*Pr_{base}[n])"
          f"/(1+12.7*((f_{base}[n]/8)^0.5)*(Pr_{base}[n]^(2/3)-1))",
          f"  hc_{base}[n] = Nu_{base}[n]*k_{base}[n]/D",
          f"  Ueff_{base}[n] = hc_{base}[n]   \"film only; wall added once per cell\"",
          "END", "")
    w('"--- cycle states ---"')
    cold_states = {"comp1_in", "comp1_out", "cooler_in", "LTR_HP_out"}
    recomp_states = {"comp2_in", "comp2_out"}
    for i in sorted(S):
        n = S[i]
        flow = ("m_dot_tube_cold" if n in cold_states else
                "frac_recomp*m_dot_tube_hot" if n in recomp_states else
                "m_dot_tube_hot")
        w(f"cp_{n} = " + _lk('cp',  f"P_{n}*Convert(bar,Pa)", f"T_{n}"),
          f"k_{n}  = " + _lk('k',   f"P_{n}*Convert(bar,Pa)", f"T_{n}"),
          f"mu_{n} = " + _lk('eta', f"P_{n}*Convert(bar,Pa)", f"T_{n}"),
          f"Pr_{n} = mu_{n}*cp_{n}/k_{n}",
          f"Re_{n} = {flow}*D/(A_flow_tube*mu_{n})",
          f"f_{n}  = (1.82*Log10(Re_{n}) - 1.64)^(-2)",
          f"Nu_{n} = ((f_{n}/8)*(Re_{n}-1000)*Pr_{n})/(1+12.7*((f_{n}/8)^0.5)*(Pr_{n}^(2/3)-1))",
          f"hc_{n} = Nu_{n}*k_{n}/D",
          f"Ueff_{n} = hc_{n}", "")


def refprop_states() -> None:
    banner("EQUILIBRIUM PROPERTIES (REFPROP)")
    w('"Interior points: h and s come from ONE flash each, not two (C6.1).',
      ' h is output slot 5 and s is slot 6."')
    for base in SIDE_NAMES:
        w("DUPLICATE n=1,d_p",
          f"  CALL EES_REFPROP(Mixture$, TP, T_{base}[n], P_{base}[n], z_CO2 : , , rho_{base}[n], , "
          f"h_{base}[n], s_{base}[n], , , , , , , , , )",
          "END")
    w("",
      '"Cycle states whose h and s follow from T and P."')
    for i in [4, 5, 7, 8, 9, 10, 11, 12]:
        n = S[i]
        w(f"CALL EES_REFPROP(Mixture$, TP, T_{n}, P_{n}, z_CO2 : , , rho_{n}, , h_{n}, s_{n}, , , , , , , , , )")
    w("",
      f"T_{S[1]} = T_cold",
      f"T_{S[5]} = T_hot",
      "",
      '"!! LEGACY INCONSISTENCY, PRESERVED DELIBERATELY (see checkpoint C0.13).',
      f'  The line below evaluates h and s at P_L, but the pressure network puts this state at',
      f'  P_{S[1]} = P_{S[10]} = P_{S[8]}, which is BELOW P_L by both low-pressure-side drops.',
      f'  The transport lookups above already use P_{S[1]}, so the state is evaluated at two',
      "  different pressures. Reproduced as-is so that C2.5 tests the rename and nothing else.",
      f'  The fix is to use P_{S[1]} here; do it as a separate change, with its own delta-eta."',
      f"CALL EES_REFPROP(Mixture$, TP, T_{S[1]}, P_L, z_CO2 : , , rho_{S[1]}, , h_{S[1]}, s_{S[1]}, , , , , , , , , )",
      "",
      f"T_{S[9]}  = T_{S[8]}",
      f"T_{S[10]} = T_{S[8]}")



def pressure_drop_segments() -> None:
    """C5.1 Steps 0 and B. Per-segment drop from LOCAL density.

    0.5*rho*v^2 with v = m_dot/(rho*A) is m_dot^2/(2*rho*A^2), so only density is
    needed - and it comes free from slot 3 of the TP call. Re and f are already per
    point from stage 5, and Re never depended on density at all.

    d_p+1 segments of length L/(d_p+1) span the tube exactly. The legacy chain
    applied dP/d_p across d_p+1 increments, over-counting by (d_p+1)/d_p = 1.25% at
    d_p=80; this form removes that as a side effect.

    Units check cleanly, unlike the legacy block: f and dL/D are dimensionless and
    m_dot^2/(rho*A^2) is kg/(m-s^2) = Pa.
    """
    banner("C5.1 - per-segment pressure drop from local density")
    w("dL_HTR = L_HTR/(d_p+1)   \"segment length\"",
      "dL_LTR = L_LTR/(d_p+1)",
      "")
    sides = [("HTR_HP", "m_dot_tube_hot",  "dL_HTR", S[12]),
             ("HTR_LP", "m_dot_tube_hot",  "dL_HTR", S[6]),
             ("LTR_HP", "m_dot_tube_cold", "dL_LTR", S[2]),
             ("LTR_LP", "m_dot_tube_hot",  "dL_LTR", S[7])]
    for base, flow, dL, s_in in sides:
        w(f'"--- {base}: {flow}; inlet segment charged at {s_in} ---"',
          f"dPin_{base} = f_{s_in}*({dL}/D)"
          f"*({flow}^2/(2*rho_{s_in}*A_flow_tube^2))*Convert(Pa,bar)",
          "DUPLICATE n=1,d_p",
          f"  dP_seg_{base}[n] = f_{base}[n]*({dL}/D)"
          f"*({flow}^2/(2*rho_{base}[n]*A_flow_tube^2))*Convert(Pa,bar)",
          "END",
          f"dP_new_{base} = dPin_{base} + Sum(dP_seg_{base}[1..d_p])   \"reportable total\"",
          "")


def machines() -> None:
    banner("COMPRESSORS AND TURBINE")
    for tag, ins, outs, eff, sign in [
            ("Main compressor", S[1], S[2], "eta_comp1", "comp"),
            ("Recompressor",    S[8], S[3], "eta_comp2", "comp"),
            ("Turbine",         S[5], S[6], "eta_turb",  "turb")]:
        w(f'"{tag}: {ins} -> {outs}"',
          f"s_i_{outs} = s_{ins}   \"isentropic\"",
          f"CALL EES_REFPROP(Mixture$, PS, P_{outs}, s_i_{outs}, z_CO2 : , , , , h_i_{outs}, , , , , , , , , , )")
        if sign == "comp":
            w(f"h_{outs} = h_{ins} + (h_i_{outs} - h_{ins})/{eff}")
        else:
            w(f"h_{outs} = h_{ins} - (h_{ins} - h_i_{outs})*{eff}")
        w(f"CALL EES_REFPROP(Mixture$, PH, P_{outs}, h_{outs}, z_CO2 : , , , , , s_{outs}, , , , , , , , , )",
          f"CALL EES_REFPROP(Mixture$, TP, T_{outs}, P_{outs}, z_CO2 : , , rho_{outs}, , , s_{outs}, , , , , , , , , )",
          "")


def recuperator(tag: str, hp: str, lp: str, area: str,
                hp_in: str, hp_out: str, lp_in: str, lp_out: str,
                m_hp: str, m_lp: str) -> None:
    banner(f"{tag} - {hp} against {lp}")
    w(f'"Cell 1: bounded by ({hp_in}, {lp_out}) on the left and n=1 on the right."',
      f"{m_hp}*(h_{hp}[1] - h_{hp_in}) = {m_lp}*(h_{lp}[1] - h_{lp_out})",
      f"Q_cell_{tag}[1] = {m_lp}*(h_{lp}[1] - h_{lp_out})",
      f"dTavg_{tag}[1] = ((T_{lp}[1]-T_{hp}[1]) + (T_{lp_out}-T_{hp_in}))/2",
      f"1/U_cell_{tag}[1] = 2/(Ueff_{lp}[1]+Ueff_{hp}[1]) + 2/(Ueff_{lp_out}+Ueff_{hp_in}) + R_cond",
      f"U_cell_{tag}[1]*({area}/(d_p+1))*dTavg_{tag}[1] = Q_cell_{tag}[1]",
      f"dT_{tag}[1] = T_{lp_out} - T_{hp_in}",
      "",
      f'"Interior cells 2..d_p, each between points m-1 and m."',
      "DUPLICATE m=2,d_p",
      f"  Q_cell_{tag}[m] = {m_hp}*(h_{hp}[m] - h_{hp}[m-1])",
      f"  Q_cell_{tag}[m] = {m_lp}*(h_{lp}[m] - h_{lp}[m-1])",
      f"  dTavg_{tag}[m] = ((T_{lp}[m]-T_{hp}[m]) + (T_{lp}[m-1]-T_{hp}[m-1]))/2",
      f"  1/U_cell_{tag}[m] = 2/(Ueff_{lp}[m]+Ueff_{hp}[m]) + 2/(Ueff_{lp}[m-1]+Ueff_{hp}[m-1]) + R_cond",
      f"  U_cell_{tag}[m]*({area}/(d_p+1))*dTavg_{tag}[m] = Q_cell_{tag}[m]",
      f"  dT_{tag}[m] = T_{lp}[m-1] - T_{hp}[m-1]",
      "END",
      "",
      f'"Cell d_p+1: bounded by n=d_p on the left and ({hp_out}, {lp_in}) on the right."',
      f"{m_hp}*(h_{hp_out} - h_{hp}[d_p]) = {m_lp}*(h_{lp_in} - h_{lp}[d_p])",
      f"Q_cell_{tag}[d_p+1] = {m_lp}*(h_{lp_in} - h_{lp}[d_p])",
      f"dTavg_{tag}[d_p+1] = ((T_{lp_in}-T_{hp_out}) + (T_{lp}[d_p]-T_{hp}[d_p]))/2",
      f"1/U_cell_{tag}[d_p+1] = 2/(Ueff_{lp_in}+Ueff_{hp_out}) + 2/(Ueff_{lp}[d_p]+Ueff_{hp}[d_p]) + R_cond",
      f"U_cell_{tag}[d_p+1]*({area}/(d_p+1))*dTavg_{tag}[d_p+1] = Q_cell_{tag}[d_p+1]",
      f"dT_{tag}[d_p+1] = T_{lp}[d_p] - T_{hp}[d_p]",
      f"dT_{tag}[d_p+2] = T_{lp_in} - T_{hp_out}",
      "",
      f"dT_min_{tag} = Min(dT_{tag}[1..(d_p+2)])",
      f"dT_avg_{tag} = Average(dT_{tag}[1..(d_p+2)])")


def closure() -> None:
    banner("MIXING, PERFORMANCE, ENTROPY GENERATION")
    w('"Mixing junction"',
      f"m_dot_{S[11]}*h_{S[11]} + m_dot_{S[3]}*h_{S[3]} = m_dot_{S[12]}*h_{S[12]}",
      f"S_gen_mixing = m_dot_{S[12]}*s_{S[12]} - (m_dot_{S[11]}*s_{S[11]} + m_dot_{S[3]}*s_{S[3]})",
      "",
      '"Work and heat"',
      f"W_dot_turb   = m_dot_{S[4]}*(h_{S[5]} - h_{S[6]})",
      f"W_dot_comp_1 = m_dot_{S[1]}*(h_{S[2]} - h_{S[1]})",
      f"W_dot_comp_2 = m_dot_{S[9]}*(h_{S[3]} - h_{S[8]})",
      "W_dot_net = W_dot_turb - W_dot_comp_1 - W_dot_comp_2",
      f"Q_dot_in  = m_dot_{S[4]}*(h_{S[5]} - h_{S[4]})",
      f"Q_dot_out = m_dot_{S[1]}*(h_{S[8]} - h_{S[1]})",
      "eta = W_dot_net/Q_dot_in",
      "",
      '"Entropy generation"',
      f"S_gen_LTR = m_dot_{S[11]}*s_{S[11]} + m_dot_{S[8]}*s_{S[8]} - m_dot_{S[2]}*s_{S[2]} - m_dot_{S[7]}*s_{S[7]}",
      f"S_gen_HTR = m_dot_{S[4]}*s_{S[4]} + m_dot_{S[7]}*s_{S[7]} - m_dot_{S[12]}*s_{S[12]} - m_dot_{S[6]}*s_{S[6]}",
      f"S_gen_heater = m_dot_{S[5]}*s_{S[5]} - m_dot_{S[4]}*s_{S[4]} - Q_dot_in/T_hot",
      f"S_gen_cooler = m_dot_{S[1]}*s_{S[1]} - m_dot_{S[10]}*s_{S[10]} + Q_dot_out/T_cold",
      "S_gen_total = S_gen_LTR + S_gen_HTR + S_gen_heater + S_gen_cooler + S_gen_mixing")


def plot_arrays() -> None:
    banner("CYCLE ARRAYS FOR PHASE-DIAGRAM PLOTTING")
    w('"Aliases in the LEGACY index order, so T_cyc[i] equals the old T[i] exactly.',
      ' EES plots all members of an array in one step, which is what these are for.',
      ' The recuperator sides are already arrays (T_HTR_HP[] etc.) and need no alias."')
    for i in sorted(S):
        n = S[i]
        w(f"T_cyc[{i}] = T_{n}   \"{n}\"")
    w("")
    for prop in ("P", "h", "s"):
        for i in sorted(S):
            w(f"{prop}_cyc[{i}] = {prop}_{S[i]}")
        w("")


def units() -> None:
    banner("UNITS (C0.12)")
    per_side = {"T": "K", "P": "bar", "h": "J/kg", "s": "J/kg-K", "cp": "J/kg-K",
                "k": "W/m-K", "mu": "kg/m-s", "Pr": "-", "Re": "-", "f": "-",
                "Nu": "-", "hc": "W/m^2-K", "Ueff": "W/m^2-K",
                "rho": "kg/m^3"}   # dP_cell is per-side only, added below
    for base in SIDE_NAMES:
        for p, u in per_side.items():
            w(f"$VarInfo {p}_{base}[] Units='{u}'")
        w("")
    for i in sorted(S):
        n = S[i]
        for p, u in per_side.items():
            w(f"$VarInfo {p}_{n} Units='{u}'")
        w(f"$VarInfo m_dot_{n} Units='kg/s'")
        w("")
    for tag, area in (("HTR", "A_HTR"), ("LTR", "A_LTR")):
        w(f"$VarInfo Q_cell_{tag}[] Units='W'",
          f"$VarInfo U_cell_{tag}[] Units='W/m^2-K'",
          f"$VarInfo dTavg_{tag}[] Units='K'",
          f"$VarInfo dT_{tag}[] Units='K'",
          f"$VarInfo dT_min_{tag} Units='K'",
          f"$VarInfo dT_avg_{tag} Units='K'", "")
    # guesses measured in Step A: per-segment mean = dP_new/(d_p+1)
    seg_guess = {"HTR_HP": "6.9e-4", "HTR_LP": "2.1e-3",
                 "LTR_HP": "1.4e-4", "LTR_LP": "1.4e-3"}
    # Upper = 0.5 bar. True per-segment drops are 1e-4..2e-3 bar, and the frozen
    # density block this replaced gave 2.2-5.6 bar for a whole side, so anything
    # approaching this bound means the density or the geometry is wrong.
    for base in SIDE_NAMES:
        g = seg_guess[base]
        w(f"$VarInfo dP_seg_{base}[] Guess={g} Lower=0 Upper=0.5 Units='bar'",
          f"$VarInfo dPin_{base} Guess={g} Lower=0 Upper=0.5 Units='bar'",
          f"$VarInfo dP_new_{base} Units='bar'")
    w("$VarInfo dL_HTR Units='m'", "$VarInfo dL_LTR Units='m'",
      "")
    for p, u in (("T_cyc[]", "K"), ("P_cyc[]", "bar"), ("h_cyc[]", "J/kg"), ("s_cyc[]", "J/kg-K")):
        w(f"$VarInfo {p} Units='{u}'")
    w("")
    for v, u in (("T_crit", "K"), ("P_crit", "bar"), ("rho_crit", "kg/m^3"),
                 ("R_cond", "m^2-K/W"), ("k_ss", "W/m-K"), ("L_ss", "m"),
                 ("A_tot", "m^2"), ("A_LTR", "m^2"), ("A_HTR", "m^2"),
                 ("A_flow_tube", "m^2"), ("A_HTR_tube", "m^2"), ("A_LTR_tube", "m^2"),
                 ("L_HTR", "m"), ("L_LTR", "m"),
                 ("m_dot_hot", "kg/s"), ("m_dot_cold", "kg/s"), ("m_dot_recomp", "kg/s"),
                 ("Q_dot_in", "W"), ("Q_dot_out", "W"), ("W_dot_net", "W"),
                 ("W_dot_turb", "W"), ("W_dot_comp_1", "W"), ("W_dot_comp_2", "W"),
                 ("S_gen_LTR", "W/K"), ("S_gen_HTR", "W/K"), ("S_gen_heater", "W/K"),
                 ("S_gen_cooler", "W/K"), ("S_gen_mixing", "W/K"), ("S_gen_total", "W/K"),
                 ("eta", "-"), ("r", "-"), ("frac_recomp", "-"),
                 ("eta_comp1", "-"), ("eta_comp2", "-"), ("eta_turb", "-"),
                 ("d_p", "-"), ("N_tubes", "-"), ("x_CO2", "-"), ("z_CO2", "-")):
        w(f"$VarInfo {v} Units='{u}'")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--table-homotopy", action="store_true",
                    help="blend old and new property tables through hom_tab; "
                         "requires both sets loaded, named cp_old/cp_new etc.")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "eqns_named.txt")
    args = ap.parse_args()
    global TABLE_HOM
    TABLE_HOM = args.table_homotopy

    header(); inputs(); areas_flows(); pressures(); transport(); refprop_states()
    pressure_drop_segments(); machines()
    recuperator("HTR", "HTR_HP", "HTR_LP", "A_HTR",
                S[12], S[4], S[6], S[7], "m_dot_hot", "m_dot_hot")
    recuperator("LTR", "LTR_HP", "LTR_LP", "A_LTR",
                S[2], S[11], S[7], S[8], "m_dot_cold", "m_dot_hot")
    closure(); plot_arrays(); units()

    text = "\n".join(L) + "\n"
    args.out.write_text(text, encoding="utf-8", newline="\r\n")
    marks = ('"', "{")
    n_eq = sum(1 for x in L if x.strip() and not x.lstrip().startswith(marks))
    print(f"  wrote {args.out}")
    print(f"  {len(L)} lines, {n_eq} non-comment")
    for bad in ("12+", "d_p+n", "[t+", "[b+", "[q-", "[p+", "[kk]"):
        assert bad not in text, f"legacy index arithmetic leaked in: {bad}"
    print("  no legacy index arithmetic present")


if __name__ == "__main__":
    main()
